# Jekyll configuration
title: Misterblue
name: Misterblue
email: misterblue-mb@misterblue.com
description: >
  Not 'blue' like the mood, but blue like the sky, blue like the bird, blue like the ocean.

# url is currently only used only for the RSS feed in feed.xml
url: "http://blog.misterblue.com"

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
#baseurl: '/mb-test'
baseurl: ''

# This can be '' to hide the Github nav button
github: ''

# Set this to your UA-# value, or '' to disable the block completely
gaaccount: 'UA-63061357-1'

comments: true

# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: 'MisterblueMisterblue'

# Set this to your public isso URL to enable comments via isso. Set to '' to disable isso.
isso: ''

sass:
    style: compressed

permalink: /:year/:year-:month-:day-:title
paginate: 5

highlighter: rouge
markdown: kramdown
gems: ['jekyll-paginate']
encoding: utf-8

excerpt_separator: <!-- more -->

exclude: ['README.md', 'LICENSE']
